pub use interpret::compile_and_interpret;

#[path = "a25_ast.rs"]
pub mod ast;
#[path = "a30_build_mir.rs"]
pub mod build_mir;
#[path = "a31_build_mir_err.rs"]
pub mod build_mir_err;
#[path = "b10_errors.rs"]
pub mod errors;
#[path = "a40_interpret.rs"]
pub mod interpret;
#[path = "a36_intrinsics.rs"]
pub mod intrinsics;
#[path = "a10_lexer.rs"]
pub mod lexer;
#[path = "a35_mir.rs"]
pub mod mir;
#[path = "a20_parser.rs"]
pub mod parser;
#[path = "a21_parser_err.rs"]
pub mod parser_err;
#[path = "b04_pos.rs"]
pub mod pos;
#[path = "a41_runtime_err.rs"]
pub mod runtime_err;
#[path = "a45_runtime_value.rs"]
pub mod runtime_value;
#[path = "b05_span.rs"]
pub mod span;
#[path = "a15_token.rs"]
pub mod token;
#[path = "a34_types.rs"]
pub mod types;
