#[path = "a25_ast.rs"]
pub mod ast;
#[path = "a30_build_mir.rs"]
pub mod build_mir;
#[path = "b10_errors.rs"]
pub mod errors;
#[path = "a40_interpret.rs"]
pub mod interpret;
#[path = "a10_lexer.rs"]
pub mod lexer;
#[path = "a35_mir.rs"]
pub mod mir;
#[path = "a20_parser.rs"]
pub mod parser;
#[path = "a21_parser_err.rs"]
pub mod parser_err;
#[path = "a15_token.rs"]
pub mod token;

#[path = "a31_build_mir_err.rs"]
pub mod build_mir_err;
