name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    name: Build and deploy static site
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install JS dependencies
        run: (cd site && npm ci)

      - name: Build for web
        run: ./scripts/build-site.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          BRANCH: gh-pages
          FOLDER: public-deploy
          single-commit: true
